[project]
name = "steamscraping"
version = "0.1.0"
description = "Game market data collection pipeline"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.2",
    "marimo>=0.18.3",
    "tqdm>=4.67.1",
    "pandera>=0.20.0",
    "pandas>=2.2.0",
]